package com.example.homeworks

val mapOfNumbers = mapOf(
    0 to "",
    1 to "ერთი",
    2 to "ორი",
    3 to "სამი",
    4 to "ოთხი",
    5 to "ხუთი",
    6 to "ექვსი",
    7 to "შვიდი",
    8 to "რვა",
    9 to "ცხრა",
    10 to "ათი",
    11 to "თერთმეტი",
    12 to "თორმეტი",
    13 to "ცამეტი",
    14 to "თოთხმეტი",
    15 to "თხუთმეტი",
    16 to "თექვსმეტი",
    17 to "ჩვიდმეტი",
    18 to "თვრამეტი",
    19 to "ცხრამეტი",
    20 to "ოც",
    40 to "ორმოც",
    60 to "სამოც",
    80 to "ოთხმოც",
    100 to "ას",
    1000 to "ათასი",


    )

val mapOfNumEng = mapOf(
    0 to "",
    1 to "one ",
    2 to "two ",
    3 to "three ",
    4 to "four ",
    5 to "five ",
    6 to "six ",
    8 to "eight ",
    9 to "nine ",
    10 to "ten",
    11 to "eleven",
    12 to "twelve",
    13 to "thirteen",
    14 to "fourteen",
    15 to "fifteen",
    16 to "sixteen",
    17 to "seventeen",
    18 to "eighteen",
    19 to "nineteen",
    20 to "twenty",
    30 to "thirty",
    40 to "forty",
    50 to "fifty",
    60 to "sixty",
    70 to "seventy",
    80 to "eighty",
    90 to "ninety",
    100 to "hundred ",
    1000 to "thousand "
)

